# fly.toml app configuration file generated for zero2prod-joshb-green-sun-4407 on 2024-04-12T15:20:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'zero2prod-joshb-green-sun-4407'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health_check]
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/health_check'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
